### ISSUE TITLE
[Android] Native animated module is not available

### ISSUE THREAD

**Issue by joncursi** [exponentjs/react-native-action-sheet#12]
After implementing an action sheet per the code recommended in the README, it will open perfectly fine on iOS, but errors out on Android:

![screen shot 2016-07-24 at 7 02 28 pm](https://cloud.githubusercontent.com/assets/4974609/17087146/33081eb4-51d1-11e6-9d2d-48bb06032004.png)

**Comment by steinnes** [comment]
I had this issue as well.  I was a little confused when debugging because the way to avoid the issue is to avoid passing `useNativeDriver: true` in Animated properties, however the source here on GitHub does not do so, ever.

That's when I noticed the version I had installed from npm was `0.2.0`, and reviewing the code in my `node_modules` folder I noticed `useNativeDriver: true` was being used in that version.

I "fixed" this in our project by pinning us to version `0.1.3`, the latest release here on GitHub, but I am curious why `0.2.0` isn't here.  Was it released to npmjs.org by accident?

**Comment by BigPun86** [comment]
+1

**Comment by rturk** [comment]
Same issue here. @steinnes tks. I've also `fixed` by manually removing `useNativeDriver: true` in node_modules.

**Comment by rturk** [comment]
Hi @ide can you publish a new minor version and a new npm package?

**Comment by brentvatne** [comment]
I published `0.2.1`, let me know if that fixes your issue!

**Comment by steinnes** [comment]
@brentvatne just tested `0.2.1` in our project, works fine!

**Comment by kfiroo** [comment]
@brentvatne I think checking for `NativeModules.NativeAnimatedModule` is not enough because we are using `transform` which it not supported in all RN versions.

I'm getting the following error:
![image](https://cloud.githubusercontent.com/assets/284636/17837729/c49f2824-67c3-11e6-90fe-99df07ecee2f.png)

Any suggestions?

**Comment by joncursi** [comment]
same issue as @kfiroo above

**Comment by kfiroo** [comment]
@joncursi opened a new issue for this https://github.com/exponentjs/react-native-action-sheet/issues/15

**Comment by lylynguyen** [comment]
I'm working with an older version of RN (0.35.0) and ran into the same issue as @joncursi above but on iOS. I fixed it by commenting our line 58 in NavigationAnimatedView.js which lives here /node_modules/react-native-experimental-navigation/NavigationAnimatedView.js.


function applyDefaultAnimation(
  position: NavigationAnimatedValue,
  navigationState: NavigationParentState,
): void {
  Animated.spring(
    position,
    {
      bounciness: 0,
      toValue: navigationState.index,
      // useNativeDriver: true,
    }
  ).start();
}
